name: end-to-end

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: "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"
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'dispatch-a',
              workflow_id: 'ci.yaml',
              ref: 'main',
            })    

