name: end-to-end


on:
  push:
    branches:
      - main
 

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: set_variables
        run: |
          AUTHOR='${{ github.triggering_actor }}'
          export MESSAGE="The author is $AUTHOR"
          echo "author=$AUTHOR" >> $GITHUB_ENV
          echo "message=$MESSAGE" >> $GITHUB_ENV
 
      - name: print
        run: |
          echo $message
          echo $author
        
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DISPATCH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'dispatch-a',
              workflow_id: 'ci.yaml',
              ref: 'main',
              inputs: {
                origin: context.repo.repo,
                author: ${{ author }}
              }
            })    

